# Video Compression Configuration
video_compression:
  # General settings
  max_file_size_mb: 10
  temp_dir: "./temp"

  # Hardware acceleration settings
  hardware_acceleration:
    nvidia: "h264_nvenc"
    amd: "h264_amf"
    fallback: "libx264"

  # Video segmentation settings - LAST RESORT only
  segmentation:
    # Enable watchdog timeout to prevent hanging ffmpeg segment encodes
    enable_timeout: true
    # Size-based thresholds (primary decision factors) - More conservative
    size_threshold_multiplier: 3.0
    fallback_duration_limit: 600

    # Segment duration preferences
    min_segment_duration: 15
    max_segment_duration: 120

    # Base durations by video length
    base_durations:
      short_video_max: 60
      short_segment_duration: 30
      medium_video_max: 180
      medium_segment_duration: 45
      long_video_max: 600
      long_segment_duration: 60
      very_long_segment_duration: 90

    # Quality adjustments for longer segments
    quality_scaling:
      enabled: true
      long_segment_fps_reduction: 0.9
      long_segment_quality_reduction: 0.95

    # Size estimation parameters
    estimation:
      default_fps: 30
      default_bitrate: "1000k"
      default_crf: 28

      aggressive_fps: 24
      aggressive_bitrate: "800k"
      aggressive_crf: 32

  # Social media platform presets
  platforms:
    instagram:
      max_width: 1080
      max_height: 1080
      aspect_ratio: "1:1"
      bitrate: "1000k"
      fps: 30

    twitter:
      max_width: 1280
      max_height: 720
      aspect_ratio: "16:9"
      bitrate: "1200k"
      fps: 30

    tiktok:
      max_width: 1080
      max_height: 1920
      aspect_ratio: "9:16"
      bitrate: "1500k"
      fps: 30

    youtube_shorts:
      max_width: 1080
      max_height: 1920
      aspect_ratio: "9:16"
      bitrate: "2000k"
      fps: 30

    facebook:
      max_width: 1280
      max_height: 720
      aspect_ratio: "16:9"
      bitrate: "1000k"
      fps: 30

    discord:
      max_width: 1280
      max_height: 720
      aspect_ratio: "16:9"
      bitrate: "800k"
      fps: 30
      max_file_size_mb: 8

  # Quality settings
  quality:
    crf: 28
    preset: "medium"
    tune: "film"
