# GIF Generation Configuration
# Note: Width and height are maximum dimensions. The actual dimensions will preserve the original video's aspect ratio.
gif_settings:
  # General settings - Platform-compatible defaults
  max_file_size_mb: 10  # Keep at 10MB for platform compatibility (Discord, etc.)
  max_duration_seconds: 30  # Allow longer content but compress aggressively
  
  # Quality settings - Improved FPS
  fps: 20  # Increased from 15 for better motion quality
  width: 360  # Maximum width (aspect ratio will be preserved)
  height: 360  # Maximum height (aspect ratio will be preserved)
  
  # Optimization settings - More balanced defaults
  palette_size: 256
  dither: "floyd_steinberg"  # Better quality default
  lossy: 60  # Reduced from 80 for better quality
  
  # Color reduction
  colors: 256
  stats_mode: "diff"  # full, diff
  
  # Segmentation settings - DISABLED for segmented videos
  segmentation:
    # Size-based thresholds (primary decision factors) - More conservative
    size_threshold_multiplier: 2.5  # Increased from 2.2 to be more conservative
    fallback_duration_limit: 180  # Increased from 120 to 3 minutes
    
    # Segment duration preferences - Shorter segments for better FPS
    min_segment_duration: 12  # Reduced from 15s for more consistent quality
    max_segment_duration: 35  # Reduced from 45s to maintain higher FPS
    
    # Base durations by video length - Optimized for FPS
    base_durations:
      short_video_max: 40  # Videos up to 40s
      short_segment_duration: 18  # Reduced from 20s for better FPS
      medium_video_max: 80  # Videos up to 80s  
      medium_segment_duration: 22  # Reduced from 25s for better FPS
      long_video_max: 120  # Videos up to 120s
      long_segment_duration: 25  # Reduced from 30s for better FPS
      very_long_segment_duration: 28  # Reduced from 35s for better FPS
    
    # Quality adjustments for longer segments - Less aggressive FPS reduction
    quality_scaling:
      enabled: true
      long_segment_fps_reduction: 0.9  # Increased from 0.8 (less FPS reduction)
      long_segment_color_reduction: 0.9  # Slightly increased from 0.875
    
    # Size estimation parameters
    estimation:
      # Parameters used for initial size estimation
      default_fps: 20  # Increased from 15 to match new base FPS
      default_colors: 256
      default_lossy: 60
      
      # Aggressive compression test parameters - Better FPS baseline
      aggressive_fps: 15  # Increased from 12 for better motion
      aggressive_colors: 192
      aggressive_lossy: 100
  
  # Quality optimization settings - Better FPS preservation
  quality_optimization:
    enabled: true  # Enable iterative quality optimization
    max_attempts_per_stage: 4  # Increased from 3 for better optimization
    target_size_efficiency: 0.95  # Slightly reduced to be more accommodating
    quality_stages:
      - name: "Maximum Quality"
        colors: 256
        fps_multiplier: 1.0
        resolution_multiplier: 1.0
        lossy: 0
        dither: "floyd_steinberg"
      - name: "High Quality"
        colors: 224  # Slightly higher than before
        fps_multiplier: 0.98  # Increased from 0.95 (less FPS reduction)
        resolution_multiplier: 0.98  # Less aggressive reduction
        lossy: 20  # Reduced from 30
        dither: "floyd_steinberg"
      - name: "Medium High Quality"  # New stage for better progression
        colors: 192
        fps_multiplier: 0.95  # Increased from 0.9 (less FPS reduction)
        resolution_multiplier: 0.95
        lossy: 40
        dither: "floyd_steinberg"
      - name: "Medium Quality"
        colors: 160  # Increased from 128
        fps_multiplier: 0.9  # Increased from 0.85 (less FPS reduction)
        resolution_multiplier: 0.92  # Less aggressive
        lossy: 60
        dither: "bayer"
      - name: "Standard Quality"
        colors: 128  # Increased from 96
        fps_multiplier: 0.85  # Increased from 0.8 (less FPS reduction)
        resolution_multiplier: 0.88  # Less aggressive
        lossy: 80  # Reduced from 100
        dither: "bayer"
      - name: "Low Quality"  # New stage for very challenging content
        colors: 96
        fps_multiplier: 0.8  # Still reduced but better than before
        resolution_multiplier: 0.8
        lossy: 120
        dither: "bayer"
  
  # Platform specific settings
  platforms:
    twitter:
      max_width: 506
      max_height: 506
      max_duration: 15
    
    discord:
      max_width: 400
      max_height: 400
      max_duration: 15  # Increased from 10
      colors: 192
      max_file_size_mb: 8  # Discord's actual 8MB limit for free users
      dither: "floyd_steinberg"
      lossy: 40
    
    slack:
      max_width: 360
      max_height: 360
      max_duration: 12  # Increased from 8
      colors: 160  # Increased for better quality
      lossy: 60 