# Logging Configuration
logging:
  version: 1
  disable_existing_loggers: false
  
  formatters:
    detailed:
      format: "[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    
    simple:
      format: "%(levelname)s - %(message)s"
    
    console:
      format: "%(asctime)s | %(levelname)-8s | %(message)s"
      datefmt: "%H:%M:%S"
  
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: console
      stream: ext://sys.stdout
      encoding: utf-8
    
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: detailed
      filename: logs/video_compressor.log
      mode: a
      encoding: utf-8
    
    error_file:
      class: logging.FileHandler
      level: ERROR
      formatter: detailed
      filename: logs/errors.log
      mode: a
      encoding: utf-8
  
  loggers:
    video_compressor:
      level: DEBUG
      handlers: [console, file, error_file]
      propagate: false
  
  root:
    level: DEBUG
    handlers: [console, file] 